"""Example of a generated FastAPI router module.

This shows what a generated router module looks like after running:
    python legacy/scripts/generate_fastapi_routers.py

DO NOT EDIT THIS FILE - It's just an example.
"""

from __future__ import annotations

from fastapi import APIRouter, Request
from starlette.responses import Response

from gateway.proxy.endpoint import proxy_to_upstream

router = APIRouter(tags=["Legacy: example_blueprint"])

@router.get("/api/v1/leads")
async def route_get_leads(request: Request) -> Response:
    """
    Proxy handler for Flask endpoint: leads.get_leads
    Original path: /api/v1/leads
    Methods: GET
    Docstring: Get all leads
    """
    return await proxy_to_upstream(request, upstream_path="/api/v1/leads")

@router.post("/api/v1/leads")
async def route_create_lead(request: Request) -> Response:
    """
    Proxy handler for Flask endpoint: leads.create_lead
    Original path: /api/v1/leads
    Methods: POST
    Docstring: Create a new lead
    """
    return await proxy_to_upstream(request, upstream_path="/api/v1/leads")

@router.get("/api/v1/leads/{lead_id:int}")
async def route_get_lead_by_id(request: Request) -> Response:
    """
    Proxy handler for Flask endpoint: leads.get_lead
    Original path: /api/v1/leads/<int:lead_id>
    Methods: GET
    Docstring: Get lead by ID
    """
    return await proxy_to_upstream(request, upstream_path="/api/v1/leads/{lead_id}")
