#!/usr/bin/env python3
"""
Helper script to wire generated legacy routers into main.py.

This script updates src/gateway/main.py to include all generated legacy routers
before the catch-all proxy router.

Usage:
    python legacy/scripts/wire_routers.py
"""

from __future__ import annotations

import re
from pathlib import Path


def find_legacy_routers() -> list[str]:
    """Find all generated legacy router modules."""
    routers_dir = Path(__file__).parent.parent.parent / "src" / "gateway" / "routers" / "legacy"
    
    if not routers_dir.exists():
        return []
    
    routers = []
    for module_file in sorted(routers_dir.glob("*.py")):
        if module_file.name == "__init__.py":
            continue
        
        module_name = module_file.stem
        routers.append(module_name)
    
    return routers


def update_main_py(routers: list[str]) -> str:
    """
    Generate code to include legacy routers in main.py.
    
    Returns the code block to insert.
    """
    if not routers:
        return ""
    
    lines = [
        "# Auto-generated legacy routers (contract-first proxies to Flask)",
        "# Generated by: python legacy/scripts/generate_fastapi_routers.py",
        "try:",
        "    from gateway.routers.legacy import all_routers as legacy_routers",
        "    # Include all legacy routers",
        "    for router in legacy_routers:",
        "        app.include_router(router)",
    ]
    
    lines.append("except ImportError:")
    lines.append("    # Legacy routers not generated yet")
    lines.append("    pass")
    lines.append("")
    
    return "\n".join(lines)


def main():
    """Main entry point."""
    routers = find_legacy_routers()
    
    if not routers:
        print("No legacy routers found. Run generate_fastapi_routers.py first.", file=sys.stderr)
        return
    
    main_py_path = Path(__file__).parent.parent.parent / "src" / "gateway" / "main.py"
    
    with open(main_py_path) as f:
        content = f.read()
    
    # Check if legacy routers are already included
    if "from gateway.routers.legacy import" in content or "legacy_routers" in content:
        print("Legacy routers already wired in main.py", file=sys.stderr)
        print("To re-wire, remove the legacy router import block first", file=sys.stderr)
        return
    
    # Find insertion point (before proxy router)
    proxy_router_pattern = r"(# Register proxy router LAST.*?\napp\.include_router\(proxy_router\))"
    
    if not re.search(proxy_router_pattern, content, re.DOTALL):
        print("ERROR: Could not find proxy router registration in main.py", file=sys.stderr)
        sys.exit(1)
    
    # Generate router inclusion code
    router_code = update_main_py(routers)
    
    # Insert before proxy router
    new_content = re.sub(
        proxy_router_pattern,
        router_code + r"\n\n\1",
        content,
        flags=re.DOTALL,
    )
    
    # Write updated main.py
    with open(main_py_path, "w") as f:
        f.write(new_content)
    
    print(f"✓ Wired {len(routers)} legacy router modules into main.py", file=sys.stderr)


if __name__ == "__main__":
    import sys
    main()
